// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Tqpv7cQJS3DKEysqK1oAS85AGCk0YrA',
    appId: '1:47007928360:web:5c77ee673fde456c1b251d',
    messagingSenderId: '47007928360',
    projectId: 'formula-33',
    authDomain: 'formula-33.firebaseapp.com',
    storageBucket: 'formula-33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPOkgV5eaqsdCzTXDWhXe8X5kPhrX13is',
    appId: '1:47007928360:android:5e3e78a3f70d51561b251d',
    messagingSenderId: '47007928360',
    projectId: 'formula-33',
    storageBucket: 'formula-33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1kdiQX_Je3rFmyQ1O9n6DxbC7ObS0T8',
    appId: '1:47007928360:ios:737ab3fb88e9a2c61b251d',
    messagingSenderId: '47007928360',
    projectId: 'formula-33',
    storageBucket: 'formula-33.appspot.com',
    iosBundleId: 'com.example.formula33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO1kdiQX_Je3rFmyQ1O9n6DxbC7ObS0T8',
    appId: '1:47007928360:ios:737ab3fb88e9a2c61b251d',
    messagingSenderId: '47007928360',
    projectId: 'formula-33',
    storageBucket: 'formula-33.appspot.com',
    iosBundleId: 'com.example.formula33',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Tqpv7cQJS3DKEysqK1oAS85AGCk0YrA',
    appId: '1:47007928360:web:6146472ce8d8ada71b251d',
    messagingSenderId: '47007928360',
    projectId: 'formula-33',
    authDomain: 'formula-33.firebaseapp.com',
    storageBucket: 'formula-33.appspot.com',
  );
}
