List<Map<String, dynamic>> questions = [
  {
    "kalimat": "Kami sekarang sedang belajar Bahasa Inggris",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 2,
    "bahasa_inggris": "We are studying English",
  },
  {
    "kalimat": "Waktu itu (kemarin), kami sedang belajar Bahasa Inggris",
    "jenis_kalimat": 0,
    "konsep_waktu": 1,
    "aspek": 0,
    "formula": 6,
    "bahasa_inggris": "We were studying English at that time",
  },
  {
    "kalimat": "Senin depan, kami sedang belajar Bahasa Inggris",
    "jenis_kalimat": 0,
    "konsep_waktu": 2,
    "aspek": 0,
    "formula": 7,
    "bahasa_inggris": "We will be studying English next Monday",
  },
  {
    "kalimat": "Kami sudah makan",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 1,
    "formula": 4,
    "bahasa_inggris": "We have eaten",
  },
  {
    "kalimat": "Dua hari yang lalu kami sudah makan",
    "jenis_kalimat": 0,
    "konsep_waktu": 1,
    "aspek": 1,
    "formula": 8,
    "bahasa_inggris": "We have eaten two days ago",
  },
  {
    "kalimat": "Mobilnya sedang direparasi sekarang",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 26,
    "bahasa_inggris": "The car is being repaired",
  },
  {
    "kalimat": "Saya 33 tahun",
    "jenis_kalimat": 1,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 12,
    "bahasa_inggris": "I am 33 years old",
  },
  {
    "kalimat": "Saya seorang pegawai negeri sipil",
    "jenis_kalimat": 1,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 12,
    "bahasa_inggris": "I am a civil servant",
  },
  {
    "kalimat": "Saya mengajar bahasa Inggris",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 0,
    "bahasa_inggris": "I teach English",
  },
  {
    "kalimat": "Saya tinggal di Yogyakarta",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 0,
    "bahasa_inggris": "I live in Yogyakarta",
  },
  {
    "kalimat": "Internet datang dan menampilkan demokrasi informasi",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 0,
    "bahasa_inggris": "Gliders only use gravity and hot air currents",
  },
  {
    "kalimat": "Ribuan karyawan Lenovo dipecat tahun 2009",
    "jenis_kalimat": 2,
    "konsep_waktu": 1,
    "aspek": 1,
    "formula": 27,
    "bahasa_inggris": "Thousands of Lenovo employees were fired in 2009",
  },
  {
    "kalimat": "Dua minggu yang lalu, dia akan berada di bandung",
    "jenis_kalimat": 2,
    "konsep_waktu": 1,
    "aspek": 2,
    "formula": 29,
    "bahasa_inggris": "Two weeks ago, he would be in Bandung",
  },
  {
    "kalimat": "Aku bangga padanya",
    "jenis_kalimat": 1,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 12,
    "bahasa_inggris": "I am proud of him",
  },
  {
    "kalimat": "Glider hanya menggunakan gaya gravitasi dan arus udara panas",
    "jenis_kalimat": 0,
    "konsep_waktu": 0,
    "aspek": 0,
    "formula": 0,
    "bahasa_inggris": "Gliders only use gravity and hot air currents",
  },
];
