var questions = [
  {
    "kalimat": "Kami sekarang sedang belajar Bahasa Inggris",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are kerjaing",
  },
  {
    "kalimat": "Waktu itu (kemarin), kami sedang belajar Bahasa Inggris",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Lampau",
    "aspek": "ke-sedang-an",
    "formula": "was/were kerjaing",
  },
  {
    "kalimat": "Saya 33 tahun",
    "jenis_kalimat": "Nomina",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are",
  },
  {
    "kalimat": "Saya seorang pegawai negeri sipil",
    "jenis_kalimat": "Nomina",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are",
  },
  {
    "kalimat": "Saya mengajar bahasa Inggris",
    "jenis_kalimat": "Verba",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
  },
  {
    "kalimat": "Saya tinggal di Yogyakarta",
    "jenis_kalimat": "Verba",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
  },
  {
    "kalimat": "Internet datang dan menampilkan demokrasi informasi",
    "jenis_kalimat": "Verba",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
  },
  {
    "kalimat": "Ribuan karyawan Lenovo dipecat tahun 2009",
    "jenis_kalimat": "Pasif",
    "konsep_waktu": "Lampau",
    "aspek": "ke-sudah-an",
    "formula": "was/were being kerjaed2",
  },
  {
    "kalimat": "Glider hanya menggunakan gaya gravitasi dan arus udara panas",
    "jenis_kalimat": "Verba",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
  },
  {
    "kalimat": "Aku bangga padanya",
    "jenis_kalimat": "Nomina",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are",
  },
];
