var questions = [
  {
    "kalimat": "Kami sekarang sedang belajar Bahasa Inggris",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are kerjaing",
    "bahasa_inggris": "We are studying English",
  },
  {
    "kalimat": "Waktu itu (kemarin), kami sedang belajar Bahasa Inggris",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Lampau",
    "aspek": "ke-sedang-an",
    "formula": "was/were kerjaing",
    "bahasa_inggris": "We were studying English at that time",
  },
  {
    "kalimat": "Senin depan, kami sedang belajar Bahasa Inggris",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Akan Datang",
    "aspek": "ke-sedang-an",
    "formula": "will be kerjaing",
    "bahasa_inggris": "We will be studying English next Monday",
  },
  {
    "kalimat": "Kami sudah makan",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sudah-an",
    "formula": "have kerjaed2",
    "bahasa_inggris": "We have eaten",
  },
  {
    "kalimat": "Dua hari yang lalu kami sudah makan",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Lampau",
    "aspek": "ke-sudah-an",
    "formula": "had kerjaed2",
    "bahasa_inggris": "We have eaten two days ago",
  },
  {
    "kalimat": "Mobilnya sedang direparasi sekarang",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are being kerjaed2",
    "bahasa_inggris": "The car is being repaired",
  },
  {
    "kalimat": "Saya 33 tahun",
    "jenis_kalimat": "Nomina",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are",
    "bahasa_inggris": "I am 33 years old",
  },
  {
    "kalimat": "Saya seorang pegawai negeri sipil",
    "jenis_kalimat": "Nomina",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are",
    "bahasa_inggris": "I am a civil servant",
  },
  {
    "kalimat": "Saya mengajar bahasa Inggris",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
    "bahasa_inggris": "I teach English",
  },
  {
    "kalimat": "Saya tinggal di Yogyakarta",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
    "bahasa_inggris": "I live in Yogyakarta",
  },
  {
    "kalimat": "Internet datang dan menampilkan demokrasi informasi",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
    "bahasa_inggris": "The Internet came and presented information democracy",
  },
  {
    "kalimat": "Ribuan karyawan Lenovo dipecat tahun 2009",
    "jenis_kalimat": "Pasif",
    "konsep_waktu": "Lampau",
    "aspek": "ke-sudah-an",
    "formula": "was/were being kerjaed2",
    "bahasa_inggris": "Thousands of Lenovo employees were fired in 2009",
  },
  {
    "kalimat": "Dua minggu yang lalu, dia akan berada di bandung",
    "jenis_kalimat": "Pasif",
    "konsep_waktu": "Lampau",
    "aspek": "ke-akandatang-an",
    "formula": "would be kerjaed2",
    "bahasa_inggris": "Two weeks ago, he would be in Bandung",
  },
  {
    "kalimat": "Aku bangga padanya",
    "jenis_kalimat": "Nomina",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "is/am/are",
    "bahasa_inggris": "I am proud of him",
  },
  {
    "kalimat": "Glider hanya menggunakan gaya gravitasi dan arus udara panas",
    "jenis_kalimat": "Verbal",
    "konsep_waktu": "Sekarang",
    "aspek": "ke-sedang-an",
    "formula": "kerja",
    "bahasa_inggris": "Gliders only use gravity and hot air currents",
  },
];
